{{- if .Values.pdb.create }}
apiVersion: {{ include "gatekeeper.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "gatekeeper.fullname" . }}
  labels:
    {{- include "gatekeeper.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "gatekeeper.selectorLabels" . | nindent 6 }}
{{- end }}
