name: Lint and Test Charts

on:
  pull_request:
    paths:
      - charts/**
      - '!charts/**/README.md'

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390 # v4.1.0
        with:
          version: v3.10.1 # Also update in publish.yaml

      - name: Set up python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: "Install keycloak"
        run: |
          kubectl config use-context kind-chart-testing
          kubectl apply -f .github/manifest.yaml
          kubectl rollout status deployment/keycloak --timeout=600s

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml
